---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cra-reporter
spec:
  params:
    - name: repository
      description: the git repo url
    - name: evidence-store
      description: comments filepath
  steps:
    - name: cra-reporter
      image: alpine
      imagePullPolicy: Always
      workingDir: "/artifacts"
      command: ["/bin/sh", "-c"]
      args:
        - |
          #!/bin/sh
          
          ls -laR
          #ls -laR "$(params.evidence-store)"

      volumeMounts:
        - mountPath: /steps
          name: steps-volume

  workspaces:
    - name: artifacts
      mountPath: /artifacts
    - name: secrets
      mountPath: /secrets

  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: secrets
      secret:
        secretName: $(params.continuous-delivery-context-secret)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json