---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cra-reporter
spec:
  params:
    - name: repository
      description: the git repo url
    - name: evidence-store
      description: comments filepath

  steps:
    - name: cra-reporter
      image: icr.io/continuous-delivery/cra-comm-editor:release.1519
      imagePullPolicy: Always
      workingDir: "/artifacts"
      command: ["/bin/sh", "-c"]
      args:
        - |
          #!/bin/sh
          
          ls -laR
          #ls -laR "$(params.evidence-store)"
  workspaces:
    - name: artifacts
      mountPath: /artifacts