properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: string
    name: repository
    value: ${REPOSITORY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
  - type: generic
    name: Generic Trigger - 0
    eventListener: manual-trigger-listener
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${toolchain-terraform-cra}
  - type: git
    path: tasks
    branch: main
    service: ${toolchain-terraform-cra}
  - type: git
    path: cra
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: master
    service: ${tekton-catalog}