properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
    properties:
      - type: text
        name: repository
        value: ${toolchain-terraform-cra.parameters.repo_url}
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${toolchain-terraform-cra}
  - type: git
    path: cra
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: git
    branch: master
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: master
    service: ${tekton-catalog}